import Link from "next/link";
import { Activity, ArrowRight, Brain, Compass, Layers, Shield } from "lucide-react";
import { Panel } from "@/components/ui/Panel";
import { Stat } from "@/components/ui/Stat";
import { Gauge } from "@/components/charts/Gauge";
import { Sparkline } from "@/components/charts/Sparkline";
import { AgentBlockCard } from "@/components/panels/AgentBlockCard";
import { generateSeries, MACRO_SIGNALS, NEWS, SECTOR_ROTATION, STOCKS } from "@/lib/data";
import { fmtPct, fmtUsd } from "@/lib/utils";
import { compositeScore } from "@/lib/scoring";
import { macroAgent, sectorAgent } from "@/lib/ai";

export default function Dashboard() {
  const topStocks = STOCKS.map((s) => ({ s, comp: compositeScore(s).composite }))
    .sort((a, b) => b.comp - a.comp)
    .slice(0, 8);
  const topSectors = [...SECTOR_ROTATION].sort((a, b) => b.rsRank - a.rsRank).slice(0, 6);

  const marketTrendScore = 78;
  const liquidityScore = 72;
  const aiConfidence = 84;
  const riskScore = 28; // lower = better risk

  return (
    <div className="p-4 lg:p-6 space-y-4">
      {/* Header strip */}
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <div className="label-xs">Command Center</div>
          <h1 className="text-2xl font-bold tracking-tight">Market Intelligence Dashboard</h1>
        </div>
        <div className="flex gap-2">
          <Link href="/agent" className="btn-ai text-xs"><Brain className="h-4 w-4" />Ask AI</Link>
          <Link href="/stocks" className="btn-primary text-xs"><Activity className="h-4 w-4" />Open Screener</Link>
        </div>
      </div>

      {/* Top KPI row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div className="panel p-4 flex items-center gap-4">
          <Gauge value={marketTrendScore} label="MARKET TREND" />
          <div className="text-xs text-ink-muted leading-snug">
            <div className="text-ink font-semibold">BULL · Stage 2</div>
            Trend confirmed across SPY/QQQ; breadth thrust active.
          </div>
        </div>
        <div className="panel p-4 flex items-center gap-4">
          <Gauge value={liquidityScore} label="LIQUIDITY" />
          <div className="text-xs text-ink-muted leading-snug">
            <div className="text-ink font-semibold">Risk-On</div>
            Fed dovish; credit spreads tight; USD weak.
          </div>
        </div>
        <div className="panel p-4 flex items-center gap-4">
          <Gauge value={aiConfidence} label="AI CONFIDENCE" />
          <div className="text-xs text-ink-muted leading-snug">
            <div className="text-ink font-semibold">High</div>
            7 agents agree on direction.
          </div>
        </div>
        <div className="panel p-4 flex items-center gap-4">
          <Gauge value={100 - riskScore} label="RISK STABILITY" />
          <div className="text-xs text-ink-muted leading-snug">
            <div className="text-risk-bull font-semibold">Stable</div>
            Concentration risk in AI complex — monitor.
          </div>
        </div>
      </div>

      {/* Macro grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-2">
        {MACRO_SIGNALS.map((m) => (
          <div key={m.key} className="panel p-3">
            <div className="flex items-center justify-between">
              <span className="label-xs">{m.label}</span>
              <span className={"chip " + (m.state === "bull" ? "chip-bull" : m.state === "bear" ? "chip-bear" : "chip-neutral")}>
                {m.state}
              </span>
            </div>
            <div className="mt-1 flex items-baseline gap-2">
              <span className="text-lg font-mono font-semibold">{m.value}{m.unit || ""}</span>
              <span className={"text-[11px] font-mono " + (m.change >= 0 ? "text-risk-bull" : "text-risk-bear")}>
                {fmtPct(m.change)}
              </span>
            </div>
            <div className="text-[10px] text-ink-dim mt-1 leading-snug">{m.hint}</div>
          </div>
        ))}
      </div>

      <div className="grid lg:grid-cols-3 gap-4">
        {/* AI Market Narrative + key stats */}
        <div className="lg:col-span-2 space-y-4">
          <Panel
            title={<span className="flex items-center gap-2"><Compass className="h-4 w-4 text-accent-cyan" />Macro Narrative</span>}
            subtitle="Auto-generated by Macro Agent · refreshed every minute"
            glow
          >
            <p className="text-sm text-ink leading-relaxed">
              <strong className="text-accent-cyan">Risk-on regime confirmed.</strong> Hyperscaler AI capex
              continues to accelerate while liquidity conditions remain supportive — declining 10Y yields,
              weak USD, compressed VIX. Semiconductor, power infrastructure, and optical names remain in
              institutional accumulation. Mid-cap SaaS continues to lag; rotation into 2nd-derivative
              AI beneficiaries (power, cooling, networking) is the dominant theme.
            </p>
            <div className="mt-4 grid sm:grid-cols-3 gap-2">
              <Stat label="Regime" value="Risk-On" tone="bull" hint="Liquidity + Trend aligned" />
              <Stat label="Stage" value="Bull · 2" tone="bull" hint="Breadth thrust active" />
              <Stat label="Bias" value="Long Growth" tone="bull" hint="Trim laggards · hedge tail" />
            </div>
          </Panel>

          <Panel title={<span className="flex items-center gap-2"><Layers className="h-4 w-4 text-accent-cyan" />Sector Leadership</span>}
            action={<Link href="/sectors" className="text-xs text-accent-cyan">View matrix →</Link>}>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
              {topSectors.map((s) => (
                <div key={s.sector} className="p-3 rounded-md bg-bg-elev/40 border border-bg-line">
                  <div className="flex justify-between items-center">
                    <div className="text-xs font-semibold">{s.sector}</div>
                    <span className="text-[10px] font-mono text-accent-cyan">RS {s.rsRank}</span>
                  </div>
                  <div className="mt-1 h-1.5 rounded-full bg-bg-line overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-accent-cyan to-risk-bull"
                      style={{ width: `${s.rsRank}%` }}
                    />
                  </div>
                  <div className="mt-2 flex justify-between text-[11px] font-mono">
                    <span className="text-ink-dim">FLOW {s.flow > 0 ? "+" : ""}{s.flow}</span>
                    <span className={s.weekChange >= 0 ? "text-risk-bull" : "text-risk-bear"}>
                      {fmtPct(s.weekChange)} 1W
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </Panel>

          <Panel title="Top AI-Scored Stocks" action={<Link href="/stocks" className="text-xs text-accent-cyan">All stocks →</Link>}>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="text-[10px] uppercase font-mono text-ink-dim border-b border-bg-line">
                  <tr className="text-left">
                    <th className="py-2">Symbol</th>
                    <th>Sector</th>
                    <th className="text-right">Price</th>
                    <th className="text-right">Chg</th>
                    <th className="text-right">Mcap</th>
                    <th className="text-right">AI Score</th>
                    <th className="w-20"></th>
                  </tr>
                </thead>
                <tbody>
                  {topStocks.map(({ s, comp }) => (
                    <tr key={s.symbol} className="border-b border-bg-line/40 hover:bg-bg-elev/30">
                      <td className="py-2.5">
                        <Link href={`/stocks/${s.symbol}`} className="font-mono font-bold text-ink hover:text-accent-cyan">
                          {s.symbol}
                        </Link>
                        <div className="text-[11px] text-ink-dim">{s.name}</div>
                      </td>
                      <td className="text-[11px] text-ink-muted">{s.sector}</td>
                      <td className="text-right font-mono">${s.price.toFixed(2)}</td>
                      <td className={"text-right font-mono " + (s.change >= 0 ? "text-risk-bull" : "text-risk-bear")}>
                        {fmtPct(s.change)}
                      </td>
                      <td className="text-right font-mono text-ink-muted">{fmtUsd(s.marketCap)}</td>
                      <td className="text-right">
                        <span className={"chip " + (comp >= 75 ? "chip-bull" : comp >= 55 ? "chip-cyan" : "chip-neutral")}>{comp}</span>
                      </td>
                      <td className="text-right">
                        <div className="w-20 inline-block">
                          <Sparkline data={generateSeries(s.symbol, 60, s.price)} color={s.change >= 0 ? "#22d39a" : "#ff4d6d"} height={28} />
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Panel>
        </div>

        {/* Right column */}
        <div className="space-y-4">
          <AgentBlockCard block={macroAgent()} />
          <AgentBlockCard block={sectorAgent()} />

          <Panel title={<span className="flex items-center gap-2"><Shield className="h-4 w-4 text-accent-cyan" />Risk Pulse</span>}
            action={<Link href="/risk" className="text-xs text-accent-cyan">Risk Center →</Link>}>
            <div className="space-y-2">
              {[
                ["Portfolio Vol (20d)", "12.8%", "neutral"],
                ["Sector Concentration", "AI 64%", "bear"],
                ["Earnings Tail (≤10d)", "3 positions", "neutral"],
                ["Liquidity (cash %)", "11%", "bull"],
              ].map(([k, v, t]) => (
                <div key={k} className="data-row">
                  <span className="text-ink-muted">{k}</span>
                  <span className={"font-mono " + (t === "bull" ? "text-risk-bull" : t === "bear" ? "text-risk-bear" : "text-ink")}>{v}</span>
                </div>
              ))}
            </div>
          </Panel>

          <Panel title="Live News Feed" action={<span className="text-[10px] font-mono text-ink-dim">{NEWS.length} items</span>}>
            <div className="space-y-2 max-h-[420px] overflow-y-auto pr-1">
              {NEWS.map((n) => (
                <div key={n.id} className="p-2.5 rounded-md border border-bg-line bg-bg-elev/30">
                  <div className="flex items-center justify-between text-[10px] font-mono text-ink-dim">
                    <span>{n.source} · {new Date(n.ts).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span>
                    <span className={"chip " + (n.sentiment === "bullish" ? "chip-bull" : n.sentiment === "bearish" ? "chip-bear" : "chip-neutral")}>
                      {n.sentiment}
                    </span>
                  </div>
                  <div className="mt-1 text-xs text-ink">{n.title}</div>
                  <div className="mt-1 text-[11px] text-ink-muted">{n.summary}</div>
                  <div className="mt-1.5 flex gap-1">
                    {n.symbols.map((sym) => (
                      <Link key={sym} href={`/stocks/${sym}`} className="text-[10px] font-mono text-accent-cyan hover:underline">${sym}</Link>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      </div>
    </div>
  );
}
